# Generated by Django 6.0.5 on 2026-06-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(choices=[('scholarship', 'Scholarship'), ('sports', 'Sports'), ('news', 'News'), ('internship', 'Internship'), ('un_agency', 'UN Agency')], max_length=50)),
                ('source', models.CharField(choices=[('undp_news', 'UNDP News'), ('mastercard_scholarship', 'Mastercard Scholarship'), ('espn_football', 'ESPN Football'), ('bbc_cricket', 'BBC Cricket'), ('unicef_careers', 'UNICEF Careers')], max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_result', models.CharField(blank=True, max_length=100)),
                ('score', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=200)),
                ('eligibility', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('times_viewed', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('items_found', models.IntegerField(default=0)),
                ('items_new', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
